name: Deploy via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install and Build
      run: |
        npm install --no-audit --no-fund
        npm run build
        
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/proexpert_land
          rm -rf ./dist/*
          mkdir -p ./dist
          
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: "/var/www/proexpert_land/dist/"
        strip_components: 1 