name: Deploy LK via SSH

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'vite.config.ts'
      - 'package.json'
      - '.github/workflows/deploy-lk.yml'

jobs:
  deploy-lk:
    runs-on: ubuntu-latest

    env:
      TARGET_PATH: /var/www/prohelper_lk
      NODE_VERSION: '22'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies & build LK
        run: |
          # Полная очистка локального кэша зависимостей, чтобы сбросить возможные
          # несинхронизированные версии пакетов (react-router и т.д.)
          rm -rf node_modules package-lock.json || true
          npm install --include=dev --no-audit --no-fund
          chmod +x node_modules/.bin/* || true
          npm run build:lk

      - name: Upload artefacts to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: root
          # Копируем production-билд ЛК целиком: index.html + client/assets
          # strip_components 1 убирает корневую папку dist-lk, т.е. в target попадут
          #   ├── index.html
          #   └── client/**  (assets, manifest и т.д.)
          source: "dist-lk/**"
          target: "/var/www/prohelper_lk/"
          strip_components: 1

      - name: Clean old files on server (optional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: root
          script: |
            set -e
            mkdir -p /var/www/prohelper_lk
            # Nothing else; scp already overwrites files 