name: Deploy Marketing via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TARGET_PATH: /var/www/prohelper_marketing
      NODE_VERSION: '20'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies & build SSR
        run: |
          # Полная очистка локальной копии зависимостей
          rm -rf node_modules package-lock.json || true
          npm install --include=dev --no-audit --no-fund
          chmod +x node_modules/.bin/* || true
          npm run build   # vite build + copy-manifest

      - name: Pack artefacts
        run: |
          # Пакуем dist. Каталог prerender может отсутствовать.
          if [ -d dist/prerender ]; then
            tar -czf marketing.tgz -C dist client prerender server
          else
            tar -czf marketing.tgz -C dist client server
          fi

      - name: Upload artefacts to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: root
          source: "marketing.tgz"
          target: "/tmp/"

      - name: Deploy on server & restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: root
          script: |
            set -e
            TARGET_PATH=${{ env.TARGET_PATH }}
            # Удаляем предыдущие раскладки
            rm -rf /tmp/marketing.tgz.dir || true
            mkdir -p $TARGET_PATH
            if [ -f /tmp/marketing.tgz ]; then
              tar -xzf /tmp/marketing.tgz -C $TARGET_PATH
              rm /tmp/marketing.tgz
            else
              echo "Файл /tmp/marketing.tgz не найден" && exit 1
            fi
            cd $TARGET_PATH/server
            if [ -f package-lock.json ]; then
              npm ci --omit=dev --no-audit --no-fund
            else
              npm install --omit=dev --no-audit --no-fund
            fi
            # Перезапускаем процесс, если он уже есть; иначе стартуем новый.
            # Порт передаём через переменную окружения, флаг --port у pm2 отсутствует.
            pm2 reload prohelper-ssr || PORT=3001 pm2 start /var/www/prohelper_marketing/server/index.js --name prohelper-ssr --time
            pm2 save 